
// Project Outline

// Types
types/
    invoice.ts
    payment.ts
    database.ts
    index.ts
    delivery.ts

// Utils
utils/
    driver.ts
    readble.ts
    colorUtils.ts
    icons.ts
    index.ts
    formatter.ts

// Components
components/
    ui/
        tabs/
            Tabs.vue
            TabsContent.vue
            TabsTrigger.vue
            TabsList.vue
            index.ts
        drawer/
            DrawerOverlay.vue
            DrawerDescription.vue
            Drawer.vue
            DrawerHeader.vue
            DrawerTitle.vue
            DrawerFooter.vue
            DrawerContent.vue
            index.ts
        pagination/
            PaginationPrev.vue
            PaginationFirst.vue
            PaginationNext.vue
            PaginationLast.vue
            index.ts
            PaginationEllipsis.vue
        form/
            FormLabel.vue
            FormMessage.vue
            FormItem.vue
            injectionKeys.ts
            FormDescription.vue
            FormControl.vue
            useFormField.ts
            index.ts
        tooltip/
            Tooltip.vue
            TooltipProvider.vue
            index.ts
            TooltipTrigger.vue
            TooltipContent.vue
        chart-bar/
            index.ts
            BarChart.vue
        calendar/
            CalendarPrevButton.vue
            CalendarHeadCell.vue
            CalendarHeading.vue
            CalendarHeader.vue
            CalendarGridHead.vue
            CalendarGridRow.vue
            CalendarCell.vue
            Calendar.vue
            CalendarGrid.vue
            CalendarGridBody.vue
            index.ts
            CalendarCellTrigger.vue
            CalendarNextButton.vue
        card/
            Card.vue
            CardContent.vue
            CardTitle.vue
            CardHeader.vue
            CardFooter.vue
            index.ts
            CardDescription.vue
        navigation-menu/
            NavigationMenuViewport.vue
            NavigationMenu.vue
            NavigationMenuItem.vue
            NavigationMenuContent.vue
            NavigationMenuTrigger.vue
            NavigationMenuLink.vue
            NavigationMenuIndicator.vue
            index.ts
            NavigationMenuList.vue
        auto-form/
            dependencies.ts
            constant.ts
            AutoFormFieldArray.vue
            AutoFormFieldBoolean.vue
            AutoFormFieldEnum.vue
            utils.ts
            AutoFormFieldFile.vue
            AutoFormFieldObject.vue
            interface.ts
            AutoFormFieldDate.vue
            AutoFormLabel.vue
            index.ts
            AutoFormFieldInput.vue
            AutoFormFieldNumber.vue
            AutoFormField.vue
            AutoForm.vue
        menubar/
            MenubarRadioGroup.vue
            MenubarGroup.vue
            MenubarSubContent.vue
            MenubarSub.vue
            MenubarSubTrigger.vue
            MenubarCheckboxItem.vue
            MenubarContent.vue
            MenubarLabel.vue
            MenubarTrigger.vue
            MenubarRadioItem.vue
            MenubarSeparator.vue
            MenubarItem.vue
            MenubarShortcut.vue
            MenubarMenu.vue
            Menubar.vue
            index.ts
        progress/
            Progress.vue
            index.ts
        alert-dialog/
            AlertDialog.vue
            AlertDialogHeader.vue
            AlertDialogFooter.vue
            AlertDialogTitle.vue
            AlertDialogTrigger.vue
            AlertDialogContent.vue
            AlertDialogAction.vue
            index.ts
            AlertDialogCancel.vue
            AlertDialogDescription.vue
        input/
            index.ts
            Input.vue
        alert/
            Alert.vue
            AlertDescription.vue
            AlertTitle.vue
            index.ts
        accordion/
            AccordionTrigger.vue
            AccordionContent.vue
            AccordionItem.vue
            Accordion.vue
            index.ts
        skeleton/
            index.ts
            Skeleton.vue
        separator/
            index.ts
            Separator.vue
        toast/
            Toaster.vue
            ToastAction.vue
            ToastDescription.vue
            ToastProvider.vue
            ToastTitle.vue
            use-toast.ts
            ToastClose.vue
            ToastViewport.vue
            index.ts
            Toast.vue
        number-field/
            NumberFieldInput.vue
            NumberFieldContent.vue
            NumberField.vue
            NumberFieldDecrement.vue
            index.ts
            NumberFieldIncrement.vue
        chart/
            ChartLegend.vue
            ChartTooltip.vue
            ChartCrosshair.vue
            interface.ts
            ChartSingleTooltip.vue
            index.ts
        hover-card/
            HoverCard.vue
            index.ts
            HoverCardTrigger.vue
            HoverCardContent.vue
        checkbox/
            index.ts
            Checkbox.vue
        label/
            Label.vue
            index.ts
        chart-line/
            index.ts
            LineChart.vue
        dropdown-menu/
            DropdownMenuLabel.vue
            DropdownMenuRadioItem.vue
            DropdownMenuSeparator.vue
            DropdownMenuGroup.vue
            DropdownMenuTrigger.vue
            DropdownMenuContent.vue
            DropdownMenuShortcut.vue
            DropdownMenuCheckboxItem.vue
            DropdownMenuItem.vue
            DropdownMenuRadioGroup.vue
            DropdownMenu.vue
            index.ts
            DropdownMenuSubContent.vue
            DropdownMenuSubTrigger.vue
            DropdownMenuSub.vue
        slider/
            Slider.vue
            index.ts
        stepper/
            StepperIndicator.vue
            StepperSeparator.vue
            index.ts
            StepperDescription.vue
            Stepper.vue
            StepperItem.vue
            StepperTitle.vue
            StepperTrigger.vue
        carousel/
            CarouselItem.vue
            CarouselNext.vue
            CarouselPrevious.vue
            interface.ts
            index.ts
            CarouselContent.vue
            Carousel.vue
            useCarousel.ts
        toggle-group/
            ToggleGroup.vue
            index.ts
            ToggleGroupItem.vue
        context-menu/
            ContextMenuRadioGroup.vue
            ContextMenuSubContent.vue
            ContextMenuSubTrigger.vue
            ContextMenuLabel.vue
            ContextMenuGroup.vue
            ContextMenuCheckboxItem.vue
            ContextMenuRadioItem.vue
            ContextMenuSeparator.vue
            ContextMenuPortal.vue
            ContextMenuShortcut.vue
            ContextMenu.vue
            ContextMenuSub.vue
            ContextMenuContent.vue
            index.ts
            ContextMenuItem.vue
            ContextMenuTrigger.vue
        tags-input/
            TagsInputItemDelete.vue
            TagsInputItem.vue
            TagsInputInput.vue
            TagsInputItemText.vue
            TagsInput.vue
            index.ts
        toggle/
            index.ts
            Toggle.vue
        dialog/
            DialogTitle.vue
            DialogHeader.vue
            DialogFooter.vue
            DialogContent.vue
            DialogTrigger.vue
            DialogScrollContent.vue
            Dialog.vue
            DialogDescription.vue
            DialogClose.vue
            index.ts
        popover/
            Popover.vue
            PopoverContent.vue
            index.ts
            PopoverTrigger.vue
        sonner/
            Sonner.vue
            index.ts
        textarea/
            index.ts
            Textarea.vue
        button/
            index.ts
            Button.vue
        scroll-area/
            ScrollArea.vue
            ScrollBar.vue
            index.ts
        table/
            TableCell.vue
            TableCaption.vue
            TableFooter.vue
            TableHead.vue
            TableHeader.vue
            TableRow.vue
            TableEmpty.vue
            index.ts
            Table.vue
            TableBody.vue
        range-calendar/
            RangeCalendarCell.vue
            RangeCalendarGridHead.vue
            RangeCalendarNextButton.vue
            RangeCalendarHeadCell.vue
            RangeCalendar.vue
            RangeCalendarCellTrigger.vue
            RangeCalendarPrevButton.vue
            RangeCalendarHeader.vue
            index.ts
            RangeCalendarGridRow.vue
            RangeCalendarGridBody.vue
            RangeCalendarHeading.vue
            RangeCalendarGrid.vue
        collapsible/
            CollapsibleTrigger.vue
            CollapsibleContent.vue
            index.ts
            Collapsible.vue
        avatar/
            AvatarFallback.vue
            AvatarImage.vue
            Avatar.vue
            index.ts
        aspect-ratio/
            index.ts
            AspectRatio.vue
        switch/
            Switch.vue
            index.ts
        chart-area/
            AreaChart.vue
            index.ts
        resizable/
            ResizablePanelGroup.vue
            ResizableHandle.vue
            index.ts
        command/
            CommandDialog.vue
            CommandSeparator.vue
            CommandItem.vue
            CommandInput.vue
            Command.vue
            CommandGroup.vue
            CommandList.vue
            index.ts
            CommandShortcut.vue
            CommandEmpty.vue
        radio-group/
            RadioGroupItem.vue
            index.ts
            RadioGroup.vue
        select/
            SelectItem.vue
            SelectTrigger.vue
            SelectContent.vue
            SelectGroup.vue
            SelectSeparator.vue
            SelectScrollUpButton.vue
            index.ts
            SelectScrollDownButton.vue
            SelectValue.vue
            SelectLabel.vue
            Select.vue
            SelectItemText.vue
        breadcrumb/
            BreadcrumbEllipsis.vue
            BreadcrumbList.vue
            BreadcrumbSeparator.vue
            BreadcrumbLink.vue
            Breadcrumb.vue
            BreadcrumbPage.vue
            index.ts
            BreadcrumbItem.vue
        sheet/
            SheetClose.vue
            SheetDescription.vue
            Sheet.vue
            SheetFooter.vue
            SheetHeader.vue
            SheetContent.vue
            SheetTrigger.vue
            index.ts
            SheetTitle.vue
        chart-donut/
            index.ts
            DonutChart.vue
        pin-input/
            PinInputGroup.vue
            PinInput.vue
            PinInputInput.vue
            index.ts
            PinInputSeparator.vue
        badge/
            Badge.vue
            index.ts
    driver/
        DriverStats.vue
        DriverTable.vue
        DriverFilter.vue
        QualificationCell.vue
        DriverDialog.vue
    payment/
        InfoCardGroup.vue
        PayrollContainer.vue
        DriverCardList.vue
        MobilePaymentDialog.vue
        PayrollDetails.vue
        DriverInfo.vue
        InfoCard.vue
        PaymentPanel.vue
        BankInfo.vue
        FilterOptions.vue
        PaymentStatus.vue
    cards/
        OverviewCard.vue
    lib/
        utils.ts
    delivery/
        ColumnCustomizer.vue
        DeliveryHeader.vue
        DeliveryTableRow.vue
        DeliveryFilter.vue
        ExportButton.vue
        DeliveryTable.vue
        DeliveryDetailDrawer.vue
        BatchActionsMenu.vue
        DeliveryColumnSelector.vue
        DataTablePagination.vue
        __tests__/
            DeliveryTable.test.ts
    base/
        DriverSelector.vue
        FixedCard.vue
        Dashboard.vue
        CustomerDetails.vue
        AppSidebar.vue
        CustomContent.vue
        DriverItem.vue
        ButtonSwitcher.vue
        Retool.vue
        NimshipFilter.vue
    invoice/
        CustomInvoiceForm.vue
        UniuniTemplateForm.vue
        InvoiceItem.vue
        InvoiceList.vue

// Composables
composables/
    useMenu.ts
    useInvoice.ts
    useDelivery.ts
    usePayroll.ts
    useDevice.ts
    usePaymentFilters.ts
    useCustomer.ts
    useEnums.ts
    useDriver.ts
