name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9.2.0

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build

    - name: Run unit tests
      run: pnpm run test

    - name: Install Cypress
      run: pnpm add cypress

    - name: Run Cypress tests
      uses: cypress-io/github-action@v5
      with:
        build: pnpm run build
        start: pnpm start
        wait-on: 'http://localhost:3000'

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9.2.0

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build

    - name: Deploy to production
      run: |
        # Add your deployment script here
        echo "Deploying to production"
